services:
  postgres:
    image: postgres:16-alpine
    container_name: pos_kasir_postgres
    environment:
      POSTGRES_DB: pos_kasir
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pos_kasir_pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pos_kasir"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pos_kasir_pgdata:
